import 'package:flutter/material.dart';
import 'package:flutterapp/pestakurentapp/generateddaftarwidget1/generated/GeneratedGroup7085Widget.dart';
import 'package:flutterapp/pestakurentapp/generateddaftarwidget1/generated/GeneratedGroup7083Widget.dart';
import 'package:flutterapp/pestakurentapp/generateddaftarwidget1/generated/GeneratedGroup7082Widget.dart';
import 'package:flutterapp/pestakurentapp/generateddaftarwidget1/generated/GeneratedGroup7084Widget.dart';

/* Component daftar
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDaftarWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 36.0,
                top: 231.0,
                right: null,
                bottom: null,
                width: 302.5,
                height: 175.0900421142578,
                child: GeneratedGroup7082Widget(),
              ),
              Positioned(
                left: 11.0,
                top: 520.0,
                right: null,
                bottom: null,
                width: 354.0,
                height: 94.0,
                child: GeneratedGroup7085Widget(),
              ),
              Positioned(
                left: 30.0,
                top: 100.0,
                right: null,
                bottom: null,
                width: 175.0,
                height: 65.0,
                child: GeneratedGroup7084Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 20.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedGroup7083Widget(),
              )
            ]),
      ),
    ));
  }
}
