import 'package:flutter/material.dart';
import 'package:flutterapp/pestakurentapp/generatedberandawidget8/generated/GeneratedGroup7167Widget1.dart';
import 'package:flutterapp/pestakurentapp/generatedberandawidget8/generated/GeneratedGroup7Widget5.dart';
import 'package:flutterapp/pestakurentapp/generatedberandawidget8/generated/GeneratedGroup7166Widget6.dart';
import 'package:flutterapp/pestakurentapp/generatedberandawidget8/generated/GeneratedGroup5Widget13.dart';
import 'package:flutterapp/pestakurentapp/generatedberandawidget8/generated/GeneratedDaftarWidget21.dart';
import 'package:flutterapp/pestakurentapp/generatedberandawidget8/generated/GeneratedLine61Widget3.dart';
import 'package:flutterapp/pestakurentapp/generatedberandawidget8/generated/GeneratedGroup14Widget4.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/pestakurentapp/generatedberandawidget8/generated/GeneratedIconlyLightOutlineProfileWidget2.dart';
import 'package:flutterapp/pestakurentapp/generatedberandawidget8/generated/GeneratedIconsaxLinearshoppingcartWidget1.dart';
import 'package:flutterapp/pestakurentapp/generatedberandawidget8/generated/GeneratedMasukWidget32.dart';

/* Component beranda
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBerandaWidget8 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: LayoutBuilder(
        builder: (BuildContext context, BoxConstraints constraints) {
      return SingleChildScrollView(
        scrollDirection: Axis.vertical,
        child: Container(
            height: 1024.0,
            child: Stack(children: [
              Container(
                  width: constraints.maxWidth,
                  child: Container(
                    width: 1440.0,
                    height: 1024.0,
                    child: Stack(
                        fit: StackFit.expand,
                        alignment: Alignment.center,
                        overflow: Overflow.visible,
                        children: [
                          ClipRRect(
                            borderRadius: BorderRadius.zero,
                            child: Container(
                              color: Color.fromARGB(255, 243, 239, 239),
                            ),
                          ),
                          Positioned(
                            left: 64.0,
                            top: 150.0,
                            right: null,
                            bottom: null,
                            width: 1141.0,
                            height: 90.0,
                            child: GeneratedGroup5Widget13(),
                          ),
                          Positioned(
                            left: 231.0,
                            top: 613.0,
                            right: null,
                            bottom: null,
                            width: 1040.0,
                            height: 36.0,
                            child: GeneratedGroup7Widget5(),
                          ),
                          Positioned(
                            left: 20.0,
                            top: 168.0,
                            right: null,
                            bottom: null,
                            width: 1380.0,
                            height: 402.0,
                            child: GeneratedGroup14Widget4(),
                          ),
                          Positioned(
                            left: 1277.0,
                            top: 168.0,
                            right: null,
                            bottom: null,
                            width: 78.0,
                            height: 78.0,
                            child: GeneratedIconsaxLinearshoppingcartWidget1(),
                          ),
                          Positioned(
                            left: 76.0,
                            top: 685.0,
                            right: null,
                            bottom: null,
                            width: 1299.0,
                            height: 282.0,
                            child: GeneratedGroup7167Widget1(),
                          ),
                          Positioned(
                            left: 560.0,
                            top: 839.0,
                            right: null,
                            bottom: null,
                            width: 168.0,
                            height: 108.0,
                            child: GeneratedGroup7166Widget6(),
                          ),
                          Positioned(
                            left: 1286.0,
                            top: 47.0,
                            right: null,
                            bottom: null,
                            width: 87.0,
                            height: 41.0,
                            child: GeneratedMasukWidget32(),
                          ),
                          Positioned(
                            left: 1195.0,
                            top: 47.0,
                            right: null,
                            bottom: null,
                            width: 79.0,
                            height: 41.0,
                            child: GeneratedDaftarWidget21(),
                          ),
                          Positioned(
                            left: 1277.4908447265625,
                            top: 90.99528503417969,
                            right: null,
                            bottom: null,
                            width: 55.0,
                            height: 1.0,
                            child: GeneratedLine61Widget3(),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width =
                                  constraints.maxWidth * 0.022000000211927627;

                              final double height =
                                  constraints.maxHeight * 0.03880937397480011;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: constraints.maxWidth *
                                        0.7861111111111111,
                                    y: constraints.maxHeight * 0.0439453125,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child:
                                          GeneratedIconlyLightOutlineProfileWidget2(),
                                    ))
                              ]);
                            }),
                          )
                        ]),
                  ))
            ])),
      );
    }));
  }
}
