import 'package:flutter/material.dart';
import 'package:flutterapp/pestakurentapp/generatedlupapasswordwidget1/generated/GeneratedTorecoveryourpasswordyouneedtoenteryourregisterdemailad.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/pestakurentapp/generatedlupapasswordwidget1/generated/GeneratedEllipse18Widget1.dart';
import 'package:flutterapp/pestakurentapp/generatedlupapasswordwidget1/generated/GeneratedGroup7071Widget4.dart';
import 'package:flutterapp/pestakurentapp/generatedlupapasswordwidget1/generated/GeneratedKirimKodeAktivitasiWidget.dart';
import 'package:flutterapp/pestakurentapp/generatedlupapasswordwidget1/generated/GeneratedIconlyLightOutlineArrowRightWidget2.dart';
import 'package:flutterapp/pestakurentapp/generatedlupapasswordwidget1/generated/GeneratedMasukkanAlamatEmailAndaWidget.dart';
import 'package:flutterapp/pestakurentapp/generatedlupapasswordwidget1/generated/GeneratedLupaPasswordWidget2.dart';
import 'package:flutterapp/pestakurentapp/generatedlupapasswordwidget1/generated/GeneratedButtonWidget8.dart';

/* Component Lupa Password
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLupaPasswordWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 390.0,
        height: 844.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 38.0,
                top: 593.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 60.0,
                child: GeneratedButtonWidget8(),
              ),
              Positioned(
                left: 84.0,
                top: null,
                right: null,
                bottom: null,
                width: 244.0,
                height: 26.0,
                child: TransformHelper.translate(
                    x: 0.00,
                    y: 197.00,
                    z: 0,
                    child: GeneratedKirimKodeAktivitasiWidget()),
              ),
              Positioned(
                left: 23.0,
                top: 21.0,
                right: null,
                bottom: null,
                width: 44.0,
                height: 44.0,
                child: GeneratedEllipse18Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.05140187679192959;

                  final double height =
                      constraints.maxHeight * 0.02375809954240989;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.13083713238055888,
                        y: constraints.maxHeight * 0.0632888106938222,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedIconlyLightOutlineArrowRightWidget2(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 109.0,
                top: 146.0,
                right: null,
                bottom: null,
                width: 199.0,
                height: 26.0,
                child: GeneratedLupaPasswordWidget2(),
              ),
              Positioned(
                left: 85.0,
                top: 422.0,
                right: null,
                bottom: null,
                width: 222.0,
                height: 29.0,
                child: GeneratedMasukkanAlamatEmailAndaWidget(),
              ),
              Positioned(
                left: 62.0,
                top: 260.0,
                right: null,
                bottom: null,
                width: 264.0,
                height: 110.0,
                child:
                    GeneratedTorecoveryourpasswordyouneedtoenteryourregisterdemailad(),
              ),
              Positioned(
                left: 49.0,
                top: 499.0,
                right: null,
                bottom: null,
                width: 293.0,
                height: 29.0,
                child: GeneratedGroup7071Widget4(),
              )
            ]),
      ),
    ));
  }
}
