import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/pestakurentapp/generatedhalaman4widget/generated/GeneratedGroupWidget1.dart';
import 'package:flutterapp/pestakurentapp/generatedhalaman4widget/generated/GeneratedDetailsWidget.dart';
import 'package:flutterapp/pestakurentapp/generatedhalaman4widget/generated/GeneratedStatusBar02TransparentWidget3.dart';
import 'package:flutterapp/pestakurentapp/generatedhalaman4widget/generated/GeneratedSeiko_Watch1Widget.dart';
import 'package:flutterapp/pestakurentapp/generatedhalaman4widget/generated/GeneratedGroup7Widget.dart';

/* Component Halaman 4
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHalaman4Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 390.0,
        height: 844.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 28.0,
                top: 121.0,
                right: null,
                bottom: null,
                width: 329.0,
                height: 281.0,
                child: GeneratedSeiko_Watch1Widget(),
              ),
              Positioned(
                left: 7.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedStatusBar02TransparentWidget3(),
              ),
              Positioned(
                left: 24.0,
                top: 57.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 25.0,
                child: GeneratedGroup7Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 422.0,
                right: null,
                bottom: null,
                width: 390.0,
                height: 423.0,
                child: GeneratedDetailsWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.0641025641025641;

                  final double height =
                      constraints.maxHeight * 0.02962085308056872;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.8717948717948718,
                        y: constraints.maxHeight * 0.06753554502369669,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroupWidget1(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
