import 'package:flutter/material.dart';
import 'package:flutterapp/pestakurentapp/generatedberandawidget2/generated/GeneratedDekorasiWidget2.dart';
import 'package:flutterapp/pestakurentapp/generatedberandawidget2/generated/GeneratedGroup7148Widget3.dart';
import 'package:flutterapp/pestakurentapp/generatedberandawidget2/generated/GeneratedGroup7145Widget.dart';
import 'package:flutterapp/pestakurentapp/generatedberandawidget2/generated/GeneratedRectangle2626Widget2.dart';
import 'package:flutterapp/pestakurentapp/generatedberandawidget2/generated/GeneratedGroup7101Widget2.dart';
import 'package:flutterapp/pestakurentapp/generatedberandawidget2/generated/GeneratedGroup7146Widget1.dart';
import 'package:flutterapp/pestakurentapp/generatedberandawidget2/generated/GeneratedGroup7103Widget2.dart';
import 'package:flutterapp/pestakurentapp/generatedberandawidget2/generated/GeneratedGroup7147Widget3.dart';
import 'package:flutterapp/pestakurentapp/generatedberandawidget2/generated/GeneratedGroup7102Widget2.dart';

/* Component beranda
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBerandaWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 30.0,
                top: 75.0,
                right: null,
                bottom: null,
                width: 313.0,
                height: 50.0,
                child: GeneratedGroup7101Widget2(),
              ),
              Positioned(
                left: 30.0,
                top: 173.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 40.0,
                child: GeneratedRectangle2626Widget2(),
              ),
              Positioned(
                left: 33.0,
                top: 181.0,
                right: null,
                bottom: null,
                width: 92.0,
                height: 29.0,
                child: GeneratedDekorasiWidget2(),
              ),
              Positioned(
                left: 21.0,
                top: 279.0,
                right: null,
                bottom: null,
                width: 332.0,
                height: 24.0,
                child: GeneratedGroup7102Widget2(),
              ),
              Positioned(
                left: 18.0,
                top: 332.0,
                right: null,
                bottom: null,
                width: 160.0,
                height: 215.0,
                child: GeneratedGroup7103Widget2(),
              ),
              Positioned(
                left: 18.0,
                top: 570.0,
                right: null,
                bottom: null,
                width: 160.0,
                height: 215.0,
                child: GeneratedGroup7146Widget1(),
              ),
              Positioned(
                left: 200.0,
                top: 570.0,
                right: null,
                bottom: null,
                width: 160.0,
                height: 215.0,
                child: GeneratedGroup7148Widget3(),
              ),
              Positioned(
                left: 200.0,
                top: 329.0,
                right: null,
                bottom: null,
                width: 160.0,
                height: 215.0,
                child: GeneratedGroup7147Widget3(),
              ),
              Positioned(
                left: 135.0,
                top: 173.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 25.0,
                child: GeneratedGroup7145Widget(),
              )
            ]),
      ),
    ));
  }
}
