import 'package:flutter/material.dart';
import 'package:flutterapp/pestakurentapp/generatedkonfirmsipembayaranwidget1/generated/GeneratedRectangle2678Widget1.dart';
import 'package:flutterapp/pestakurentapp/generatedkonfirmsipembayaranwidget1/generated/GeneratedSelamatpembayaranandatelahberhasilWidget1.dart';
import 'package:flutterapp/pestakurentapp/generatedkonfirmsipembayaranwidget1/generated/GeneratedKeberandaWidget1.dart';
import 'package:flutterapp/pestakurentapp/generatedkonfirmsipembayaranwidget1/generated/GeneratedATMWidget1.dart';

/* Component konfirmsi pembayaran
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedKonfirmsipembayaranWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1024.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1440.0,
                      height: 1024.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 243, 239, 239),
                              ),
                            ),
                            Positioned(
                              left: 277.0,
                              top: 160.0,
                              right: null,
                              bottom: null,
                              width: 887.0,
                              height: 62.0,
                              child:
                                  GeneratedSelamatpembayaranandatelahberhasilWidget1(),
                            ),
                            Positioned(
                              left: 470.0,
                              top: 820.0,
                              right: null,
                              bottom: null,
                              width: 500.0,
                              height: 100.0,
                              child: GeneratedRectangle2678Widget1(),
                            ),
                            Positioned(
                              left: 604.0,
                              top: 840.0,
                              right: null,
                              bottom: null,
                              width: 234.0,
                              height: 62.0,
                              child: GeneratedKeberandaWidget1(),
                            ),
                            Positioned(
                              left: 535.0,
                              top: 293.0,
                              right: null,
                              bottom: null,
                              width: 344.0,
                              height: 334.0,
                              child: GeneratedATMWidget1(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
