import 'package:flutter/material.dart';
import 'package:flutterapp/pestakurentapp/generatedcheckoutwidget/generated/GeneratedRectangle2654Widget.dart';
import 'package:flutterapp/pestakurentapp/generatedcheckoutwidget/generated/GeneratedGroup7110Widget.dart';
import 'package:flutterapp/pestakurentapp/generatedcheckoutwidget/generated/GeneratedRectangle2660Widget.dart';
import 'package:flutterapp/pestakurentapp/generatedcheckoutwidget/generated/GeneratedGroup7109Widget.dart';
import 'package:flutterapp/pestakurentapp/generatedcheckoutwidget/generated/GeneratedGroup7117Widget.dart';
import 'package:flutterapp/pestakurentapp/generatedcheckoutwidget/generated/GeneratedRentalCartWidget.dart';

/* Component checkout
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCheckoutWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 15.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 50.0,
                child: GeneratedGroup7110Widget(),
              ),
              Positioned(
                left: 15.0,
                top: 186.0,
                right: null,
                bottom: null,
                width: 269.0,
                height: 110.0,
                child: GeneratedGroup7109Widget(),
              ),
              Positioned(
                left: -1.0,
                top: 341.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 471.0,
                child: GeneratedRectangle2660Widget(),
              ),
              Positioned(
                left: 15.0,
                top: 356.0,
                right: null,
                bottom: null,
                width: 337.0,
                height: 436.0,
                child: GeneratedGroup7117Widget(),
              ),
              Positioned(
                left: 87.0,
                top: 80.0,
                right: null,
                bottom: null,
                width: 200.0,
                height: 75.0,
                child: GeneratedRectangle2654Widget(),
              ),
              Positioned(
                left: 114.0,
                top: 108.0,
                right: null,
                bottom: null,
                width: 149.0,
                height: 22.0,
                child: GeneratedRentalCartWidget(),
              )
            ]),
      ),
    ));
  }
}
