import 'package:flutter/material.dart';

/* UndefinedNode profil
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedProfilWidget4 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
