import 'package:flutter/material.dart';
import 'package:flutterapp/pestakurentapp/generatediphone1313pro2widget/generated/GeneratedAndadisinimasuksebagaitamulakukanlogindaftaruntukmelaku.dart';
import 'package:flutterapp/pestakurentapp/generatediphone1313pro2widget/generated/GeneratedWidget.dart';
import 'package:flutterapp/pestakurentapp/generatediphone1313pro2widget/generated/GeneratedMasukWidget15.dart';
import 'package:flutterapp/pestakurentapp/generatediphone1313pro2widget/generated/GeneratedRectangle2Widget4.dart';
import 'package:flutterapp/pestakurentapp/generatediphone1313pro2widget/generated/GeneratedPerhatianWidget1.dart';

/* Component iPhone 13 / 13 Pro - 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone1313Pro2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 390.0,
        height: 844.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 72.0,
                top: 83.0,
                right: null,
                bottom: null,
                width: 248.0,
                height: 63.0,
                child: GeneratedPerhatianWidget1(),
              ),
              Positioned(
                left: 25.0,
                top: 537.0,
                right: null,
                bottom: null,
                width: 341.0,
                height: 117.0,
                child:
                    GeneratedAndadisinimasuksebagaitamulakukanlogindaftaruntukmelaku(),
              ),
              Positioned(
                left: 60.0,
                top: 708.0,
                right: null,
                bottom: null,
                width: 270.0,
                height: 50.0,
                child: GeneratedRectangle2Widget4(),
              ),
              Positioned(
                left: 147.0,
                top: 715.0,
                right: null,
                bottom: null,
                width: 80.0,
                height: 38.0,
                child: GeneratedMasukWidget15(),
              ),
              Positioned(
                left: 163.0,
                top: 238.0,
                right: null,
                bottom: null,
                width: 68.0,
                height: 177.0,
                child: GeneratedWidget(),
              )
            ]),
      ),
    ));
  }
}
