import 'package:flutter/material.dart';
import 'package:flutterapp/pestakurentapp/generateddaftarwidget11/generated/GeneratedGroup7140Widget6.dart';
import 'package:flutterapp/pestakurentapp/generateddaftarwidget11/generated/GeneratedRectangle2698Widget.dart';
import 'package:flutterapp/pestakurentapp/generateddaftarwidget11/generated/GeneratedRectangle2679Widget.dart';
import 'package:flutterapp/pestakurentapp/generateddaftarwidget11/generated/GeneratedDaftarWidget12.dart';
import 'package:flutterapp/pestakurentapp/generateddaftarwidget11/generated/GeneratedDaftarWidget13.dart';

/* Component daftar
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDaftarWidget11 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1024.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1440.0,
                      height: 1024.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 44.0,
                              top: 93.0,
                              right: null,
                              bottom: null,
                              width: 300.0,
                              height: 75.0,
                              child: GeneratedRectangle2679Widget(),
                            ),
                            Positioned(
                              left: 58.0,
                              top: 118.0,
                              right: null,
                              bottom: null,
                              width: 195.0,
                              height: 29.0,
                              child: GeneratedDaftarWidget12(),
                            ),
                            Positioned(
                              left: 44.0,
                              top: 214.0,
                              right: null,
                              bottom: null,
                              width: 1365.0,
                              height: 760.0,
                              child: GeneratedGroup7140Widget6(),
                            ),
                            Positioned(
                              left: 866.0,
                              top: 709.0,
                              right: null,
                              bottom: null,
                              width: 310.0,
                              height: 65.0,
                              child: GeneratedRectangle2698Widget(),
                            ),
                            Positioned(
                              left: 964.0,
                              top: 729.0,
                              right: null,
                              bottom: null,
                              width: 118.0,
                              height: 29.0,
                              child: GeneratedDaftarWidget13(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
