import 'package:flutter/material.dart';

/* UndefinedNode kode verifikasi
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedKodeverifikasiWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
