import 'package:flutter/material.dart';
import 'package:flutterapp/pestakurentapp/generatediphone1313pro1widget2/generated/GeneratedHomeindicatorWidget12.dart';
import 'package:flutterapp/pestakurentapp/generatediphone1313pro1widget2/generated/GeneratedGroup7139Widget5.dart';
import 'package:flutterapp/pestakurentapp/generatediphone1313pro1widget2/generated/GeneratedPESTAKURENTWidget5.dart';
import 'package:flutterapp/pestakurentapp/generatediphone1313pro1widget2/generated/GeneratedCarikebutuhanpestaandadisiniWidget5.dart';
import 'package:flutterapp/pestakurentapp/generatediphone1313pro1widget2/generated/GeneratedStatusBar02TransparentWidget7.dart';
import 'package:flutterapp/pestakurentapp/generatediphone1313pro1widget2/generated/GeneratedSeries7Widget4.dart';
import 'package:flutterapp/pestakurentapp/generatediphone1313pro1widget2/generated/GeneratedHomeindicatorWidget11.dart';
import 'package:flutterapp/helpers/transform/transform.dart';

/* Component iPhone 13 / 13 Pro - 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone1313Pro1Widget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 390.0,
        height: 844.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 27, 36, 48),
                ),
              ),
              Positioned(
                left: 51.0,
                top: 72.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 177.0,
                child: GeneratedPESTAKURENTWidget5(),
              ),
              Positioned(
                left: 34.0,
                top: 578.0,
                right: null,
                bottom: null,
                width: 329.0,
                height: 31.0,
                child: GeneratedCarikebutuhanpestaandadisiniWidget5(),
              ),
              Positioned(
                left: null,
                top: 247.0,
                right: null,
                bottom: null,
                width: 314.0,
                height: 314.0,
                child: TransformHelper.translate(
                    x: 2.00, y: 0.00, z: 0, child: GeneratedSeries7Widget4()),
              ),
              Positioned(
                left: 75.0,
                top: 647.0,
                right: null,
                bottom: null,
                width: 241.0,
                height: 147.0,
                child: GeneratedGroup7139Widget5(),
              ),
              Positioned(
                left: 8.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 40.0,
                child: GeneratedStatusBar02TransparentWidget7(),
              ),
              Positioned(
                left: 8.0,
                top: 810.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 34.0,
                child: GeneratedHomeindicatorWidget11(),
              ),
              Positioned(
                left: 1.0,
                top: 812.0,
                right: null,
                bottom: null,
                width: 390.0,
                height: 34.0,
                child: GeneratedHomeindicatorWidget12(),
              )
            ]),
      ),
    ));
  }
}
