import 'package:flutter/material.dart';

/* UndefinedNode form daftar
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFormdaftarWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
