import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flutterapp/pestakurentapp/generateddekor7widget7/generated/GeneratedRectangle2701Widget1.dart';
import 'package:flutterapp/pestakurentapp/generateddekor7widget7/generated/GeneratedFrame6Widget12.dart';

/* Component Dekor 7
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDekor7Widget7 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      decoration: BoxDecoration(
        boxShadow: kIsWeb
            ? []
            : [
                BoxShadow(
                  color: Color.fromARGB(255, 11, 9, 25),
                  offset: Offset(0.0, 0.0),
                  blurRadius: 30.0,
                )
              ],
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.circular(14.0),
        child: Container(
          width: 475.0,
          height: 518.0,
          decoration: BoxDecoration(
            borderRadius: BorderRadius.circular(14.0),
          ),
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.circular(14.0),
                  child: Container(
                    color: Color.fromARGB(255, 214, 170, 251),
                  ),
                ),
                Positioned(
                  left: 25.0,
                  top: 289.0,
                  right: null,
                  bottom: null,
                  width: 194.0,
                  height: 144.0,
                  child: GeneratedFrame6Widget12(),
                ),
                Positioned(
                  left: 25.0,
                  top: 25.0,
                  right: null,
                  bottom: null,
                  width: 425.0,
                  height: 245.0,
                  child: GeneratedRectangle2701Widget1(),
                )
              ]),
        ),
      ),
    ));
  }
}
