import 'package:flutter/material.dart';

/* UndefinedNode Cell
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCellWidget20 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
