import 'package:flutter/material.dart';
import 'package:flutterapp/pestakurentapp/generatedperingatanwidget/generated/GeneratedGroup7124Widget2.dart';
import 'package:flutterapp/pestakurentapp/generatedperingatanwidget/generated/GeneratedGroup7126Widget1.dart';
import 'package:flutterapp/pestakurentapp/generatedperingatanwidget/generated/GeneratedGroup7123Widget1.dart';
import 'package:flutterapp/pestakurentapp/generatedperingatanwidget/generated/GeneratedGroup7125Widget1.dart';

/* Component peringatan
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPeringatanWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 70.0,
                top: 75.0,
                right: null,
                bottom: null,
                width: 228.0,
                height: 54.0,
                child: GeneratedGroup7126Widget1(),
              ),
              Positioned(
                left: 18.0,
                top: 462.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 163.0,
                child: GeneratedGroup7124Widget2(),
              ),
              Positioned(
                left: 53.0,
                top: 681.0,
                right: null,
                bottom: null,
                width: 270.0,
                height: 50.0,
                child: GeneratedGroup7125Widget1(),
              ),
              Positioned(
                left: 90.0,
                top: 193.0,
                right: null,
                bottom: null,
                width: 185.0,
                height: 185.0,
                child: GeneratedGroup7123Widget1(),
              )
            ]),
      ),
    ));
  }
}
