import 'package:flutter/material.dart';
import 'package:flutterapp/pestakurentapp/generatedlaporansewawidget1/generated/GeneratedGroup7153Widget6.dart';
import 'package:flutterapp/pestakurentapp/generatedlaporansewawidget1/generated/GeneratedGroup7154Widget6.dart';
import 'package:flutterapp/pestakurentapp/generatedlaporansewawidget1/generated/GeneratedLaporanSewaWidget3.dart';
import 'package:flutterapp/pestakurentapp/generatedlaporansewawidget1/generated/GeneratedSENIN12Oktober2022Widget.dart';
import 'package:flutterapp/pestakurentapp/generatedlaporansewawidget1/generated/GeneratedGroup7151Widget22.dart';
import 'package:flutterapp/pestakurentapp/generatedlaporansewawidget1/generated/GeneratedGroup7150Widget6.dart';
import 'package:flutterapp/pestakurentapp/generatedlaporansewawidget1/generated/GeneratedGroup7152Widget25.dart';
import 'package:flutterapp/pestakurentapp/generatedlaporansewawidget1/generated/GeneratedGroup7155Widget6.dart';
import 'package:flutterapp/pestakurentapp/generatedlaporansewawidget1/generated/GeneratedRectangle2701Widget2.dart';

/* Frame laporan sewa
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLaporansewaWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1024.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1440.0,
                      height: 1024.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 117.0,
                              top: 170.0,
                              right: null,
                              bottom: null,
                              width: 530.0,
                              height: 256.9696960449219,
                              child: GeneratedGroup7150Widget6(),
                            ),
                            Positioned(
                              left: 746.0,
                              top: 166.0,
                              right: null,
                              bottom: null,
                              width: 530.0,
                              height: 256.9696960449219,
                              child: GeneratedGroup7153Widget6(),
                            ),
                            Positioned(
                              left: 746.0,
                              top: 454.0,
                              right: null,
                              bottom: null,
                              width: 530.0,
                              height: 256.9696960449219,
                              child: GeneratedGroup7154Widget6(),
                            ),
                            Positioned(
                              left: 746.0,
                              top: 742.0,
                              right: null,
                              bottom: null,
                              width: 530.0,
                              height: 256.9696960449219,
                              child: GeneratedGroup7155Widget6(),
                            ),
                            Positioned(
                              left: 117.0,
                              top: 454.0,
                              right: null,
                              bottom: null,
                              width: 530.0,
                              height: 256.9696960449219,
                              child: GeneratedGroup7151Widget22(),
                            ),
                            Positioned(
                              left: 117.0,
                              top: 738.0,
                              right: null,
                              bottom: null,
                              width: 530.0,
                              height: 256.9696960449219,
                              child: GeneratedGroup7152Widget25(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 1440.0,
                              height: 144.0,
                              child: GeneratedRectangle2701Widget2(),
                            ),
                            Positioned(
                              left: 50.0,
                              top: 51.0,
                              right: null,
                              bottom: null,
                              width: 288.0,
                              height: 62.0,
                              child: GeneratedLaporanSewaWidget3(),
                            ),
                            Positioned(
                              left: 1057.0,
                              top: 79.0,
                              right: null,
                              bottom: null,
                              width: 270.0,
                              height: 38.0,
                              child: GeneratedSENIN12Oktober2022Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
