import 'package:flutter/material.dart';
import 'package:flutterapp/pestakurentapp/generatedverifikasikodewidget3/generated/GeneratedGroup7159Widget.dart';
import 'package:flutterapp/pestakurentapp/generatedverifikasikodewidget3/generated/GeneratedGroup7158Widget.dart';
import 'package:flutterapp/pestakurentapp/generatedverifikasikodewidget3/generated/GeneratedGroup7160Widget.dart';
import 'package:flutterapp/pestakurentapp/generatedverifikasikodewidget3/generated/GeneratedGroup7157Widget.dart';

/* Component verifikasi kode
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVerifikasikodeWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1024.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1440.0,
                      height: 1024.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 220.0,
                              top: 109.0,
                              right: null,
                              bottom: null,
                              width: 1000.0,
                              height: 100.0,
                              child: GeneratedGroup7158Widget(),
                            ),
                            Positioned(
                              left: 320.0,
                              top: 302.0,
                              right: null,
                              bottom: null,
                              width: 800.0,
                              height: 163.0,
                              child: GeneratedGroup7159Widget(),
                            ),
                            Positioned(
                              left: 344.0,
                              top: 558.0,
                              right: null,
                              bottom: null,
                              width: 751.0,
                              height: 130.0,
                              child: GeneratedGroup7157Widget(),
                            ),
                            Positioned(
                              left: 395.0,
                              top: 811.0,
                              right: null,
                              bottom: null,
                              width: 650.0,
                              height: 100.0,
                              child: GeneratedGroup7160Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
