import 'package:flutter/material.dart';
import 'package:flutterapp/pestakurentapp/generatedtooltipwidget1/generated/GeneratedOnlylayerstylessuchasbackgroundcolorborderradiusetcwill1.dart';
import 'package:flutterapp/pestakurentapp/generatedtooltipwidget1/generated/GeneratedArtworkWidget1.dart';

/* Instance .Tooltip
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTooltipWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 457.0,
      height: 53.0,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(8.0),
      ),
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: GeneratedArtworkWidget1(),
            ),
            Positioned(
              left: 20.0,
              top: 16.0,
              right: null,
              bottom: null,
              width: 419.0,
              height: 23.0,
              child:
                  GeneratedOnlylayerstylessuchasbackgroundcolorborderradiusetcwill1(),
            )
          ]),
    ));
  }
}
