import 'package:flutter/material.dart';
import 'package:flutterapp/pestakurentapp/generatedkeranjangwidget1/generated/GeneratedLine69Widget.dart';
import 'package:flutterapp/pestakurentapp/generatedkeranjangwidget1/generated/GeneratedLine70Widget.dart';
import 'package:flutterapp/pestakurentapp/generatedkeranjangwidget1/generated/GeneratedGroup18Widget.dart';
import 'package:flutterapp/pestakurentapp/generatedkeranjangwidget1/generated/GeneratedRectangle2702Widget.dart';
import 'package:flutterapp/pestakurentapp/generatedkeranjangwidget1/generated/GeneratedRectangle2703Widget.dart';
import 'package:flutterapp/pestakurentapp/generatedkeranjangwidget1/generated/GeneratedRectangle2700Widget.dart';
import 'package:flutterapp/pestakurentapp/generatedkeranjangwidget1/generated/GeneratedRectangle2701Widget.dart';
import 'package:flutterapp/pestakurentapp/generatedkeranjangwidget1/generated/GeneratedRectangle2705Widget.dart';
import 'package:flutterapp/pestakurentapp/generatedkeranjangwidget1/generated/GeneratedRectangle2704Widget.dart';
import 'package:flutterapp/pestakurentapp/generatedkeranjangwidget1/generated/GeneratedGroup18Widget1.dart';
import 'package:flutterapp/pestakurentapp/generatedkeranjangwidget1/generated/GeneratedRectangle2706Widget.dart';

/* Component keranjang
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedKeranjangWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1137.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1440.0,
                      height: 1024.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 50.0,
                              top: 77.0,
                              right: null,
                              bottom: null,
                              width: 1306.0,
                              height: 90.0,
                              child: GeneratedGroup18Widget(),
                            ),
                            Positioned(
                              left: 101.0,
                              top: 289.0,
                              right: null,
                              bottom: null,
                              width: 418.0,
                              height: 389.0,
                              child: GeneratedRectangle2700Widget(),
                            ),
                            Positioned(
                              left: 101.0,
                              top: 289.0,
                              right: null,
                              bottom: null,
                              width: 571.0035400390625,
                              height: 1.0,
                              child: GeneratedLine69Widget(),
                            ),
                            Positioned(
                              left: 519.0,
                              top: 286.0,
                              right: null,
                              bottom: null,
                              width: 573.0514526367188,
                              height: 1.0,
                              child: GeneratedLine70Widget(),
                            ),
                            Positioned(
                              left: 550.0,
                              top: 346.0,
                              right: null,
                              bottom: null,
                              width: 304.0,
                              height: 51.0,
                              child: GeneratedRectangle2701Widget(),
                            ),
                            Positioned(
                              left: 550.0,
                              top: 427.0,
                              right: null,
                              bottom: null,
                              width: 304.0,
                              height: 48.0,
                              child: GeneratedRectangle2702Widget(),
                            ),
                            Positioned(
                              left: 550.0,
                              top: 505.0,
                              right: null,
                              bottom: null,
                              width: 750.0,
                              height: 45.0,
                              child: GeneratedRectangle2703Widget(),
                            ),
                            Positioned(
                              left: 550.0,
                              top: 575.0,
                              right: null,
                              bottom: null,
                              width: 750.0,
                              height: 45.0,
                              child: GeneratedRectangle2704Widget(),
                            ),
                            Positioned(
                              left: 550.0,
                              top: 645.0,
                              right: null,
                              bottom: null,
                              width: 750.0,
                              height: 45.0,
                              child: GeneratedRectangle2705Widget(),
                            ),
                            Positioned(
                              left: 50.0,
                              top: 761.0,
                              right: null,
                              bottom: null,
                              width: 313.0,
                              height: 53.0,
                              child: GeneratedRectangle2706Widget(),
                            ),
                            Positioned(
                              left: 36.0,
                              top: 855.0,
                              right: null,
                              bottom: null,
                              width: 1292.0,
                              height: 282.0,
                              child: GeneratedGroup18Widget1(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
