import 'package:flutter/material.dart';
import 'package:flutterapp/pestakurentapp/generatedverifikasikodewidget2/generated/GeneratedRectangle2604Widget2.dart';
import 'package:flutterapp/pestakurentapp/generatedverifikasikodewidget2/generated/GeneratedGroup7093Widget2.dart';
import 'package:flutterapp/pestakurentapp/generatedverifikasikodewidget2/generated/GeneratedKonfirmasikodeandaWidget2.dart';
import 'package:flutterapp/pestakurentapp/generatedverifikasikodewidget2/generated/GeneratedKonfirmasiWidget6.dart';
import 'package:flutterapp/pestakurentapp/generatedverifikasikodewidget2/generated/GeneratedGroup7087Widget2.dart';
import 'package:flutterapp/pestakurentapp/generatedverifikasikodewidget2/generated/GeneratedGroup7088Widget2.dart';
import 'package:flutterapp/pestakurentapp/generatedverifikasikodewidget2/generated/GeneratedRectangle2613Widget2.dart';
import 'package:flutterapp/pestakurentapp/generatedverifikasikodewidget2/generated/GeneratedRectangle2614Widget2.dart';
import 'package:flutterapp/pestakurentapp/generatedverifikasikodewidget2/generated/GeneratedGroup7089Widget2.dart';

/* Instance verifikasi kode 
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVerifikasikodeWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 24.0,
                top: 32.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 50.0,
                child: GeneratedGroup7089Widget2(),
              ),
              Positioned(
                left: 53.0,
                top: 445.0,
                right: null,
                bottom: null,
                width: 252.0,
                height: 50.0,
                child: GeneratedGroup7093Widget2(),
              ),
              Positioned(
                left: 37.0,
                top: 541.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 60.0,
                child: GeneratedGroup7087Widget2(),
              ),
              Positioned(
                left: 50.0,
                top: 140.0,
                right: null,
                bottom: null,
                width: 275.0,
                height: 40.0,
                child: GeneratedRectangle2604Widget2(),
              ),
              Positioned(
                left: 54.0,
                top: 148.0,
                right: null,
                bottom: null,
                width: 269.0,
                height: 26.0,
                child: GeneratedKonfirmasikodeandaWidget2(),
              ),
              Positioned(
                left: 112.0,
                top: 650.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 20.0,
                child: GeneratedRectangle2613Widget2(),
              ),
              Positioned(
                left: 100.0,
                top: 375.0,
                right: null,
                bottom: null,
                width: 175.0,
                height: 15.0,
                child: GeneratedRectangle2614Widget2(),
              ),
              Positioned(
                left: 37.0,
                top: 255.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 54.0,
                child: GeneratedGroup7088Widget2(),
              ),
              Positioned(
                left: 122.0,
                top: 559.0,
                right: null,
                bottom: null,
                width: 135.0,
                height: 29.0,
                child: GeneratedKonfirmasiWidget6(),
              )
            ]),
      ),
    ));
  }
}
