import 'package:flutter/material.dart';
import 'package:flutterapp/pestakurentapp/generatedprofilwidget6/generated/GeneratedGroup7150Widget3.dart';
import 'package:flutterapp/pestakurentapp/generatedprofilwidget6/generated/GeneratedGroup7151Widget11.dart';
import 'package:flutterapp/pestakurentapp/generatedprofilwidget6/generated/GeneratedKeluarWidget5.dart';

/* Component profil
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedProfilWidget6 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1024.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1440.0,
                      height: 1024.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 108.0,
                              top: 223.0,
                              right: null,
                              bottom: null,
                              width: 1225.0,
                              height: 750.0,
                              child: GeneratedGroup7150Widget3(),
                            ),
                            Positioned(
                              left: 108.0,
                              top: 75.0,
                              right: null,
                              bottom: null,
                              width: 230.0,
                              height: 90.0,
                              child: GeneratedGroup7151Widget11(),
                            ),
                            Positioned(
                              left: 1036.0,
                              top: 860.0,
                              right: null,
                              bottom: null,
                              width: 119.0,
                              height: 59.0,
                              child: GeneratedKeluarWidget5(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
