import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/pestakurentapp/generatedkonfirmasipasswordbaruwidget/generated/GeneratedEllipse18Widget3.dart';
import 'package:flutterapp/pestakurentapp/generatedkonfirmasipasswordbaruwidget/generated/GeneratedGroup7080Widget2.dart';
import 'package:flutterapp/pestakurentapp/generatedkonfirmasipasswordbaruwidget/generated/GeneratedIconlyLightOutlineArrowRightWidget4.dart';
import 'package:flutterapp/pestakurentapp/generatedkonfirmasipasswordbaruwidget/generated/GeneratedKonfirmasiPasswordBaruWidget1.dart';
import 'package:flutterapp/pestakurentapp/generatedkonfirmasipasswordbaruwidget/generated/GeneratedEnterNewPasswordWidget.dart';
import 'package:flutterapp/pestakurentapp/generatedkonfirmasipasswordbaruwidget/generated/GeneratedButtonWidget12.dart';
import 'package:flutterapp/pestakurentapp/generatedkonfirmasipasswordbaruwidget/generated/GeneratedGroup7081Widget4.dart';
import 'package:flutterapp/pestakurentapp/generatedkonfirmasipasswordbaruwidget/generated/GeneratedSilakanmasukkankatasandibaruAndakonfirmasiuntukmenikmat.dart';

/* Component Konfirmasi Password Baru
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedKonfirmasiPasswordBaruWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 390.0,
        height: 844.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 23.0,
                top: 25.0,
                right: null,
                bottom: null,
                width: 44.0,
                height: 44.0,
                child: GeneratedEllipse18Widget3(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.05140187679192959;

                  final double height =
                      constraints.maxHeight * 0.023758097282518143;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.13083713238055888,
                        y: constraints.maxHeight * 0.06292672179886515,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedIconlyLightOutlineArrowRightWidget4(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 45.0,
                top: 185.0,
                right: null,
                bottom: null,
                width: 301.0,
                height: 39.0,
                child: GeneratedKonfirmasiPasswordBaruWidget1(),
              ),
              Positioned(
                left: 83.0,
                top: 430.0,
                right: null,
                bottom: null,
                width: 264.0,
                height: 29.0,
                child: GeneratedEnterNewPasswordWidget(),
              ),
              Positioned(
                left: 46.0,
                top: 240.0,
                right: null,
                bottom: null,
                width: 308.0,
                height: 83.0,
                child:
                    GeneratedSilakanmasukkankatasandibaruAndakonfirmasiuntukmenikmat(),
              ),
              Positioned(
                left: 52.0,
                top: 493.0,
                right: null,
                bottom: null,
                width: 294.0,
                height: 29.000015258789062,
                child: GeneratedGroup7080Widget2(),
              ),
              Positioned(
                left: 53.0,
                top: 558.0,
                right: null,
                bottom: null,
                width: 294.0,
                height: 29.00000762939453,
                child: GeneratedGroup7081Widget4(),
              ),
              Positioned(
                left: 37.0,
                top: 643.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 60.0,
                child: GeneratedButtonWidget12(),
              )
            ]),
      ),
    ));
  }
}
