import 'package:flutter/material.dart';
import 'package:flutterapp/pestakurentapp/generatedberandawidget1/generated/GeneratedRectangle2626Widget1.dart';
import 'package:flutterapp/pestakurentapp/generatedberandawidget1/generated/GeneratedDekorasiWidget.dart';
import 'package:flutterapp/pestakurentapp/generatedberandawidget1/generated/GeneratedGroup7102Widget1.dart';
import 'package:flutterapp/pestakurentapp/generatedberandawidget1/generated/GeneratedGroup7104Widget1.dart';
import 'package:flutterapp/pestakurentapp/generatedberandawidget1/generated/GeneratedLine32Widget1.dart';
import 'package:flutterapp/pestakurentapp/generatedberandawidget1/generated/GeneratedGroup7103Widget1.dart';
import 'package:flutterapp/pestakurentapp/generatedberandawidget1/generated/GeneratedGroup7105Widget1.dart';
import 'package:flutterapp/pestakurentapp/generatedberandawidget1/generated/GeneratedGroup7101Widget1.dart';
import 'package:flutterapp/pestakurentapp/generatedberandawidget1/generated/GeneratedLine33Widget1.dart';
import 'package:flutterapp/pestakurentapp/generatedberandawidget1/generated/GeneratedGroup7106Widget1.dart';

/* Component beranda
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBerandaWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 30.0,
                top: 75.0,
                right: null,
                bottom: null,
                width: 313.0,
                height: 50.0,
                child: GeneratedGroup7101Widget1(),
              ),
              Positioned(
                left: 30.0,
                top: 173.0,
                right: null,
                bottom: null,
                width: 135.0,
                height: 40.0,
                child: GeneratedRectangle2626Widget1(),
              ),
              Positioned(
                left: 30.0,
                top: 181.0,
                right: null,
                bottom: null,
                width: 110.0,
                height: 29.0,
                child: GeneratedDekorasiWidget(),
              ),
              Positioned(
                left: 18.0,
                top: 279.0,
                right: null,
                bottom: null,
                width: 342.0,
                height: 24.0,
                child: GeneratedGroup7102Widget1(),
              ),
              Positioned(
                left: 14.0,
                top: 329.0,
                right: null,
                bottom: null,
                width: 160.0,
                height: 215.0,
                child: GeneratedGroup7103Widget1(),
              ),
              Positioned(
                left: 187.0,
                top: 329.0,
                right: null,
                bottom: null,
                width: 160.0,
                height: 215.0,
                child: GeneratedGroup7104Widget1(),
              ),
              Positioned(
                left: 14.0,
                top: 558.0,
                right: null,
                bottom: null,
                width: 160.0,
                height: 215.0,
                child: GeneratedGroup7105Widget1(),
              ),
              Positioned(
                left: 187.0,
                top: 558.0,
                right: null,
                bottom: null,
                width: 160.0,
                height: 215.0,
                child: GeneratedGroup7106Widget1(),
              ),
              Positioned(
                left: 159.0,
                top: 88.0,
                right: null,
                bottom: null,
                width: 33.241539001464844,
                height: 1.0,
                child: GeneratedLine32Widget1(),
              ),
              Positioned(
                left: 135.0,
                top: 88.0,
                right: null,
                bottom: null,
                width: 33.941123962402344,
                height: 1.0,
                child: GeneratedLine33Widget1(),
              )
            ]),
      ),
    ));
  }
}
