import 'package:flutter/material.dart';
import 'package:flutterapp/pestakurentapp/generatedmasukwidget1/generated/GeneratedGroup7071Widget.dart';
import 'package:flutterapp/pestakurentapp/generatedmasukwidget1/generated/GeneratedGroup7099Widget.dart';
import 'package:flutterapp/pestakurentapp/generatedmasukwidget1/generated/GeneratedGroup7100Widget.dart';
import 'package:flutterapp/pestakurentapp/generatedmasukwidget1/generated/GeneratedGroup7095Widget.dart';
import 'package:flutterapp/pestakurentapp/generatedmasukwidget1/generated/GeneratedRectangle2621Widget.dart';
import 'package:flutterapp/pestakurentapp/generatedmasukwidget1/generated/GeneratedRectangle2685Widget.dart';

/* Component masuk
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMasukWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 19.0,
                top: 19.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 50.0,
                child: GeneratedGroup7095Widget(),
              ),
              Positioned(
                left: 31.0,
                top: 112.0,
                right: null,
                bottom: null,
                width: 200.0,
                height: 72.0,
                child: GeneratedGroup7100Widget(),
              ),
              Positioned(
                left: 12.0,
                top: 331.7662353515625,
                right: null,
                bottom: null,
                width: 350.0000915527344,
                height: 106.23371887207031,
                child: GeneratedGroup7071Widget(),
              ),
              Positioned(
                left: 37.0,
                top: 619.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 60.0,
                child: GeneratedGroup7099Widget(),
              ),
              Positioned(
                left: 100.0,
                top: 506.0,
                right: null,
                bottom: null,
                width: 175.0,
                height: 25.0,
                child: GeneratedRectangle2621Widget(),
              ),
              Positioned(
                left: 75.0,
                top: 713.0,
                right: null,
                bottom: null,
                width: 225.0,
                height: 25.0,
                child: GeneratedRectangle2685Widget(),
              )
            ]),
      ),
    ));
  }
}
