import 'package:flutter/material.dart';
import 'package:flutterapp/pestakurentapp/generatedcheckoutwidget4/generated/GeneratedRentalcartWidget.dart';
import 'package:flutterapp/pestakurentapp/generatedcheckoutwidget4/generated/GeneratedRectangle2669Widget2.dart';
import 'package:flutterapp/pestakurentapp/generatedcheckoutwidget4/generated/GeneratedGroup7136Widget3.dart';
import 'package:flutterapp/pestakurentapp/generatedcheckoutwidget4/generated/GeneratedRectangle2666Widget1.dart';
import 'package:flutterapp/pestakurentapp/generatedcheckoutwidget4/generated/GeneratedCheckoutWidget5.dart';

/* Component checkout
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCheckoutWidget4 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1024.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1440.0,
                      height: 1024.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 638.432373046875,
                              top: 312.4705810546875,
                              right: null,
                              bottom: null,
                              width: 691.567626953125,
                              height: 457.058837890625,
                              child: GeneratedGroup7136Widget3(),
                            ),
                            Positioned(
                              left: 50.0,
                              top: 48.0,
                              right: null,
                              bottom: null,
                              width: 318.0,
                              height: 94.0,
                              child: GeneratedRectangle2666Widget1(),
                            ),
                            Positioned(
                              left: 77.0,
                              top: 83.0,
                              right: null,
                              bottom: null,
                              width: 255.0,
                              height: 26.0,
                              child: GeneratedRentalcartWidget(),
                            ),
                            Positioned(
                              left: 370.0,
                              top: 868.0,
                              right: null,
                              bottom: null,
                              width: 498.0,
                              height: 100.0,
                              child: GeneratedRectangle2669Widget2(),
                            ),
                            Positioned(
                              left: 482.0,
                              top: 918.0,
                              right: null,
                              bottom: null,
                              width: 240.0,
                              height: 26.0,
                              child: GeneratedCheckoutWidget5(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
