import 'package:flutter/material.dart';
import 'package:flutterapp/pestakurentapp/generatedberandawidget/generated/GeneratedLine32Widget.dart';
import 'package:flutterapp/pestakurentapp/generatedberandawidget/generated/GeneratedGroup7102Widget.dart';
import 'package:flutterapp/pestakurentapp/generatedberandawidget/generated/GeneratedGroup7106Widget.dart';
import 'package:flutterapp/pestakurentapp/generatedberandawidget/generated/GeneratedGroup7105Widget.dart';
import 'package:flutterapp/pestakurentapp/generatedberandawidget/generated/GeneratedGroup7101Widget.dart';
import 'package:flutterapp/pestakurentapp/generatedberandawidget/generated/GeneratedGroup7103Widget.dart';
import 'package:flutterapp/pestakurentapp/generatedberandawidget/generated/GeneratedGroup7104Widget.dart';
import 'package:flutterapp/pestakurentapp/generatedberandawidget/generated/GeneratedRectangle2626Widget.dart';
import 'package:flutterapp/pestakurentapp/generatedberandawidget/generated/GeneratedLine33Widget.dart';

/* Component beranda
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBerandaWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 30.0,
                top: 75.0,
                right: null,
                bottom: null,
                width: 313.0,
                height: 50.0,
                child: GeneratedGroup7101Widget(),
              ),
              Positioned(
                left: 30.0,
                top: 173.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 40.0,
                child: GeneratedRectangle2626Widget(),
              ),
              Positioned(
                left: 18.0,
                top: 281.0,
                right: null,
                bottom: null,
                width: 342.0,
                height: 20.0,
                child: GeneratedGroup7102Widget(),
              ),
              Positioned(
                left: 14.0,
                top: 329.0,
                right: null,
                bottom: null,
                width: 160.0,
                height: 215.0,
                child: GeneratedGroup7103Widget(),
              ),
              Positioned(
                left: 187.0,
                top: 329.0,
                right: null,
                bottom: null,
                width: 160.0,
                height: 215.0,
                child: GeneratedGroup7104Widget(),
              ),
              Positioned(
                left: 14.0,
                top: 558.0,
                right: null,
                bottom: null,
                width: 160.0,
                height: 215.0,
                child: GeneratedGroup7105Widget(),
              ),
              Positioned(
                left: 187.0,
                top: 558.0,
                right: null,
                bottom: null,
                width: 160.0,
                height: 215.0,
                child: GeneratedGroup7106Widget(),
              ),
              Positioned(
                left: 159.0,
                top: 88.0,
                right: null,
                bottom: null,
                width: 33.241539001464844,
                height: 1.0,
                child: GeneratedLine32Widget(),
              ),
              Positioned(
                left: 135.0,
                top: 88.0,
                right: null,
                bottom: null,
                width: 33.941123962402344,
                height: 1.0,
                child: GeneratedLine33Widget(),
              )
            ]),
      ),
    ));
  }
}
