import 'package:flutter/material.dart';
import 'package:flutterapp/pestakurentapp/generateddaftarwidget22/generated/GeneratedDaftarWidget23.dart';
import 'package:flutterapp/pestakurentapp/generateddaftarwidget22/generated/GeneratedDaftarWidget24.dart';
import 'package:flutterapp/pestakurentapp/generateddaftarwidget22/generated/GeneratedIconsaxOutlinepasswordcheckWidget1.dart';
import 'package:flutterapp/pestakurentapp/generateddaftarwidget22/generated/GeneratedIconsaxOutlineprofileWidget1.dart';
import 'package:flutterapp/pestakurentapp/generateddaftarwidget22/generated/GeneratedRectangle2681Widget7.dart';
import 'package:flutterapp/pestakurentapp/generateddaftarwidget22/generated/GeneratedIconsaxOutlinecallWidget.dart';
import 'package:flutterapp/pestakurentapp/generateddaftarwidget22/generated/GeneratedGroup7140Widget10.dart';
import 'package:flutterapp/pestakurentapp/generateddaftarwidget22/generated/GeneratedHideWidget.dart';
import 'package:flutterapp/pestakurentapp/generateddaftarwidget22/generated/GeneratedMessageWidget3.dart';
import 'package:flutterapp/pestakurentapp/generateddaftarwidget22/generated/GeneratedRectangle2698Widget6.dart';
import 'package:flutterapp/pestakurentapp/generateddaftarwidget22/generated/GeneratedProfileWidget5.dart';
import 'package:flutterapp/pestakurentapp/generateddaftarwidget22/generated/GeneratedIconsaxOutlinekeyWidget2.dart';
import 'package:flutterapp/pestakurentapp/generateddaftarwidget22/generated/GeneratedIconsaxOutlinekeyWidget1.dart';
import 'package:flutterapp/pestakurentapp/generateddaftarwidget22/generated/GeneratedRectangle2679Widget4.dart';

/* Component daftar
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDaftarWidget22 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1024.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1440.0,
                      height: 1024.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 243, 239, 239),
                              ),
                            ),
                            Positioned(
                              left: 44.0,
                              top: 93.0,
                              right: null,
                              bottom: null,
                              width: 300.0,
                              height: 75.0,
                              child: GeneratedRectangle2679Widget4(),
                            ),
                            Positioned(
                              left: 58.0,
                              top: 118.0,
                              right: null,
                              bottom: null,
                              width: 195.0,
                              height: 29.0,
                              child: GeneratedDaftarWidget23(),
                            ),
                            Positioned(
                              left: 44.0,
                              top: 214.0,
                              right: null,
                              bottom: null,
                              width: 1365.0,
                              height: 760.0,
                              child: GeneratedGroup7140Widget10(),
                            ),
                            Positioned(
                              left: 866.0,
                              top: 709.0,
                              right: null,
                              bottom: null,
                              width: 310.0,
                              height: 65.0,
                              child: GeneratedRectangle2698Widget6(),
                            ),
                            Positioned(
                              left: 964.0,
                              top: 729.0,
                              right: null,
                              bottom: null,
                              width: 118.0,
                              height: 29.0,
                              child: GeneratedDaftarWidget24(),
                            ),
                            Positioned(
                              left: 751.0,
                              top: 343.0,
                              right: null,
                              bottom: null,
                              width: 48.0,
                              height: 48.0,
                              child: GeneratedProfileWidget5(),
                            ),
                            Positioned(
                              left: 751.0,
                              top: 533.0,
                              right: null,
                              bottom: null,
                              width: 48.0,
                              height: 48.0,
                              child: GeneratedMessageWidget3(),
                            ),
                            Positioned(
                              left: 1663.930419921875,
                              top: 600.0895385742188,
                              right: null,
                              bottom: null,
                              width: 48.0,
                              height: 48.0,
                              child: GeneratedHideWidget(),
                            ),
                            Positioned(
                              left: 93.0,
                              top: 369.0,
                              right: null,
                              bottom: null,
                              width: 500.0,
                              height: 500.0,
                              child: GeneratedRectangle2681Widget7(),
                            ),
                            Positioned(
                              left: 751.0,
                              top: 341.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 50.0,
                              child: GeneratedIconsaxOutlineprofileWidget1(),
                            ),
                            Positioned(
                              left: 749.0,
                              top: 437.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 50.0,
                              child: GeneratedIconsaxOutlinecallWidget(),
                            ),
                            Positioned(
                              left: 1196.0,
                              top: 623.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 50.0,
                              child:
                                  GeneratedIconsaxOutlinepasswordcheckWidget1(),
                            ),
                            Positioned(
                              left: 750.0,
                              top: 623.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 50.0,
                              child: GeneratedIconsaxOutlinekeyWidget1(),
                            ),
                            Positioned(
                              left: 729.0,
                              top: 624.0,
                              right: null,
                              bottom: null,
                              width: 24.0,
                              height: 24.0,
                              child: GeneratedIconsaxOutlinekeyWidget2(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
