import 'package:flutter/material.dart';
import 'package:flutterapp/pestakurentapp/generatedlaporansewawidget/generated/GeneratedGroup7152Widget16.dart';
import 'package:flutterapp/pestakurentapp/generatedlaporansewawidget/generated/GeneratedGroup7153Widget4.dart';
import 'package:flutterapp/pestakurentapp/generatedlaporansewawidget/generated/GeneratedLaporanSewaWidget2.dart';
import 'package:flutterapp/pestakurentapp/generatedlaporansewawidget/generated/GeneratedGroup7156Widget2.dart';
import 'package:flutterapp/pestakurentapp/generatedlaporansewawidget/generated/GeneratedGroup7154Widget4.dart';
import 'package:flutterapp/pestakurentapp/generatedlaporansewawidget/generated/GeneratedGroup7150Widget4.dart';
import 'package:flutterapp/pestakurentapp/generatedlaporansewawidget/generated/GeneratedGroup7155Widget4.dart';

/* Component laporan sewa
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLaporansewaWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1024.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1440.0,
                      height: 1024.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 50.0,
                              top: 51.0,
                              right: null,
                              bottom: null,
                              width: 288.0,
                              height: 62.0,
                              child: GeneratedLaporanSewaWidget2(),
                            ),
                            Positioned(
                              left: 117.0,
                              top: 170.0,
                              right: null,
                              bottom: null,
                              width: 530.0,
                              height: 256.9696960449219,
                              child: GeneratedGroup7150Widget4(),
                            ),
                            Positioned(
                              left: 775.0,
                              top: 170.0,
                              right: null,
                              bottom: null,
                              width: 530.0,
                              height: 256.9696960449219,
                              child: GeneratedGroup7154Widget4(),
                            ),
                            Positioned(
                              left: 775.0,
                              top: 453.0,
                              right: null,
                              bottom: null,
                              width: 530.0,
                              height: 256.9696960449219,
                              child: GeneratedGroup7155Widget4(),
                            ),
                            Positioned(
                              left: 775.0,
                              top: 736.0,
                              right: null,
                              bottom: null,
                              width: 530.0,
                              height: 256.9696960449219,
                              child: GeneratedGroup7156Widget2(),
                            ),
                            Positioned(
                              left: 117.0,
                              top: 453.0,
                              right: null,
                              bottom: null,
                              width: 530.0,
                              height: 256.9696960449219,
                              child: GeneratedGroup7152Widget16(),
                            ),
                            Positioned(
                              left: 117.0,
                              top: 736.0,
                              right: null,
                              bottom: null,
                              width: 530.0,
                              height: 256.9696960449219,
                              child: GeneratedGroup7153Widget4(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
