import 'package:flutter/material.dart';
import 'package:flutterapp/pestakurentapp/generateddesktop7widget/generated/GeneratedTable1Widget.dart';
import 'package:flutterapp/pestakurentapp/generateddesktop7widget/generated/GeneratedTableWidget.dart';
import 'package:flutterapp/pestakurentapp/generateddesktop7widget/generated/GeneratedTableWidget4.dart';
import 'package:flutterapp/pestakurentapp/generateddesktop7widget/generated/GeneratedTableWidget2.dart';
import 'package:flutterapp/pestakurentapp/generateddesktop7widget/generated/GeneratedShoppingCartWidget.dart';
import 'package:flutterapp/pestakurentapp/generateddesktop7widget/generated/GeneratedTableWidget5.dart';
import 'package:flutterapp/pestakurentapp/generateddesktop7widget/generated/GeneratedRectangle2707Widget.dart';
import 'package:flutterapp/pestakurentapp/generateddesktop7widget/generated/GeneratedRectangle2709Widget.dart';
import 'package:flutterapp/pestakurentapp/generateddesktop7widget/generated/GeneratedTableWidget3.dart';
import 'package:flutterapp/pestakurentapp/generateddesktop7widget/generated/GeneratedRectangle2710Widget.dart';
import 'package:flutterapp/pestakurentapp/generateddesktop7widget/generated/GeneratedKembaliBelanjaWidget.dart';
import 'package:flutterapp/pestakurentapp/generateddesktop7widget/generated/GeneratedTotalhargaWidget.dart';
import 'package:flutterapp/pestakurentapp/generateddesktop7widget/generated/GeneratedTableWidget1.dart';
import 'package:flutterapp/pestakurentapp/generateddesktop7widget/generated/GeneratedCheckoutWidget6.dart';
import 'package:flutterapp/pestakurentapp/generateddesktop7widget/generated/GeneratedRectangle2708Widget.dart';

/* Component Desktop - 7
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDesktop7Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1024.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1440.0,
                      height: 1024.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 1000.0,
                              height: 50.0,
                              child: GeneratedTableWidget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 1000.0,
                              height: 50.0,
                              child: GeneratedTableWidget1(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 1000.0,
                              height: 50.0,
                              child: GeneratedTableWidget2(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 1000.0,
                              height: 50.0,
                              child: GeneratedTableWidget3(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 1000.0,
                              height: 50.0,
                              child: GeneratedTableWidget4(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 1000.0,
                              height: 50.0,
                              child: GeneratedTableWidget5(),
                            ),
                            Positioned(
                              left: 43.0,
                              top: 230.0,
                              right: null,
                              bottom: null,
                              width: 1353.0,
                              height: 563.0,
                              child: GeneratedTable1Widget(),
                            ),
                            Positioned(
                              left: 55.0,
                              top: 71.0,
                              right: null,
                              bottom: null,
                              width: 339.0,
                              height: 85.0,
                              child: GeneratedRectangle2707Widget(),
                            ),
                            Positioned(
                              left: 80.0,
                              top: 93.0,
                              right: null,
                              bottom: null,
                              width: 248.0,
                              height: 49.0,
                              child: GeneratedShoppingCartWidget(),
                            ),
                            Positioned(
                              left: 1171.0,
                              top: 908.0,
                              right: null,
                              bottom: null,
                              width: 225.0,
                              height: 62.0,
                              child: GeneratedRectangle2708Widget(),
                            ),
                            Positioned(
                              left: 902.0,
                              top: 908.0,
                              right: null,
                              bottom: null,
                              width: 249.0,
                              height: 62.0,
                              child: GeneratedRectangle2709Widget(),
                            ),
                            Positioned(
                              left: 1151.0,
                              top: 813.0,
                              right: null,
                              bottom: null,
                              width: 195.0,
                              height: 39.0,
                              child: GeneratedRectangle2710Widget(),
                            ),
                            Positioned(
                              left: 1155.0,
                              top: 813.0,
                              right: null,
                              bottom: null,
                              width: 161.0,
                              height: 41.0,
                              child: GeneratedTotalhargaWidget(),
                            ),
                            Positioned(
                              left: 1210.0,
                              top: 919.0,
                              right: null,
                              bottom: null,
                              width: 141.0,
                              height: 44.0,
                              child: GeneratedCheckoutWidget6(),
                            ),
                            Positioned(
                              left: 915.0,
                              top: 919.0,
                              right: null,
                              bottom: null,
                              width: 225.0,
                              height: 41.0,
                              child: GeneratedKembaliBelanjaWidget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
