import 'package:flutter/material.dart';
import 'package:flutterapp/pestakurentapp/generatedlaporanbarangseewaanwidget/generated/GeneratedKonfirmasiWidget5.dart';
import 'package:flutterapp/pestakurentapp/generatedlaporanbarangseewaanwidget/generated/GeneratedLaporanSewaWidget.dart';
import 'package:flutterapp/pestakurentapp/generatedlaporanbarangseewaanwidget/generated/GeneratedGroup7152Widget2.dart';
import 'package:flutterapp/pestakurentapp/generatedlaporanbarangseewaanwidget/generated/GeneratedRectangle2689Widget.dart';
import 'package:flutterapp/pestakurentapp/generatedlaporanbarangseewaanwidget/generated/GeneratedGroup7151Widget1.dart';
import 'package:flutterapp/pestakurentapp/generatedlaporanbarangseewaanwidget/generated/GeneratedGroup7153Widget.dart';
import 'package:flutterapp/pestakurentapp/generatedlaporanbarangseewaanwidget/generated/GeneratedGroup7150Widget.dart';

/* Component laporan barang seewaan
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLaporanbarangseewaanWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 23.0,
                top: 97.0,
                right: null,
                bottom: null,
                width: 330.0,
                height: 160.0,
                child: GeneratedGroup7150Widget(),
              ),
              Positioned(
                left: 23.0,
                top: 272.0,
                right: null,
                bottom: null,
                width: 330.0,
                height: 160.0,
                child: GeneratedGroup7151Widget1(),
              ),
              Positioned(
                left: 23.0,
                top: 447.0,
                right: null,
                bottom: null,
                width: 330.0,
                height: 160.0,
                child: GeneratedGroup7152Widget2(),
              ),
              Positioned(
                left: 23.0,
                top: 622.0,
                right: null,
                bottom: null,
                width: 330.0,
                height: 160.0,
                child: GeneratedGroup7153Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 20.0,
                right: null,
                bottom: null,
                width: 174.0,
                height: 26.0,
                child: GeneratedLaporanSewaWidget(),
              ),
              Positioned(
                left: 260.0,
                top: 16.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 30.0,
                child: GeneratedRectangle2689Widget(),
              ),
              Positioned(
                left: 250.0,
                top: 394.0,
                right: null,
                bottom: null,
                width: 91.0,
                height: 29.0,
                child: GeneratedKonfirmasiWidget5(),
              )
            ]),
      ),
    ));
  }
}
