import 'package:flutter/material.dart';
import 'package:flutterapp/pestakurentapp/generatedverifikasikodewidget7/generated/GeneratedMasukkankodeverifikasiWidget2.dart';
import 'package:flutterapp/pestakurentapp/generatedverifikasikodewidget7/generated/GeneratedGroup7160Widget2.dart';
import 'package:flutterapp/pestakurentapp/generatedverifikasikodewidget7/generated/GeneratedGroup7158Widget2.dart';
import 'package:flutterapp/pestakurentapp/generatedverifikasikodewidget7/generated/GeneratedGroup7157Widget2.dart';
import 'package:flutterapp/pestakurentapp/generatedverifikasikodewidget7/generated/GeneratedMasukkankodeverifikasiyangdikirimkankeuseremailgmailcom2.dart';

/* Component verifikasi kode
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVerifikasikodeWidget7 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1024.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1440.0,
                      height: 1024.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 243, 239, 239),
                              ),
                            ),
                            Positioned(
                              left: 220.0,
                              top: 109.0,
                              right: null,
                              bottom: null,
                              width: 1009.0,
                              height: 100.0,
                              child: GeneratedGroup7158Widget2(),
                            ),
                            Positioned(
                              left: 344.0,
                              top: 558.0,
                              right: null,
                              bottom: null,
                              width: 751.0,
                              height: 130.0,
                              child: GeneratedGroup7157Widget2(),
                            ),
                            Positioned(
                              left: 395.0,
                              top: 811.0,
                              right: null,
                              bottom: null,
                              width: 650.0,
                              height: 100.0,
                              child: GeneratedGroup7160Widget2(),
                            ),
                            Positioned(
                              left: 253.0,
                              top: 264.0,
                              right: null,
                              bottom: null,
                              width: 946.0,
                              height: 167.0,
                              child:
                                  GeneratedMasukkankodeverifikasiyangdikirimkankeuseremailgmailcom2(),
                            ),
                            Positioned(
                              left: 539.0,
                              top: 454.0,
                              right: null,
                              bottom: null,
                              width: 373.0,
                              height: 60.0,
                              child: GeneratedMasukkankodeverifikasiWidget2(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
