import 'package:flutter/material.dart';
import 'package:flutterapp/pestakurentapp/generatediphone1313pro5widget/generated/GeneratedKeluarWidget3.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/pestakurentapp/generatediphone1313pro5widget/generated/GeneratedRectangle2676Widget3.dart';
import 'package:flutterapp/pestakurentapp/generatediphone1313pro5widget/generated/GeneratedRectangle2687Widget16.dart';
import 'package:flutterapp/pestakurentapp/generatediphone1313pro5widget/generated/GeneratediconarrowbackoutlineWidget3.dart';
import 'package:flutterapp/pestakurentapp/generatediphone1313pro5widget/generated/GeneratedProfilWidget3.dart';
import 'package:flutterapp/pestakurentapp/generatediphone1313pro5widget/generated/GeneratediconlogoutWidget.dart';
import 'package:flutterapp/pestakurentapp/generatediphone1313pro5widget/generated/GeneratedRectangle2686Widget2.dart';

/* Component iPhone 13 / 13 Pro - 5
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone1313Pro5Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.only(
        topLeft: Radius.circular(0.0),
        topRight: Radius.circular(25.0),
        bottomRight: Radius.circular(25.0),
        bottomLeft: Radius.circular(0.0),
      ),
      child: Container(
        width: 295.0,
        height: 844.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.only(
            topLeft: Radius.circular(0.0),
            topRight: Radius.circular(25.0),
            bottomRight: Radius.circular(25.0),
            bottomLeft: Radius.circular(0.0),
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.only(
                  topLeft: Radius.circular(0.0),
                  topRight: Radius.circular(25.0),
                  bottomRight: Radius.circular(25.0),
                  bottomLeft: Radius.circular(0.0),
                ),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 295.0,
                height: 844.0,
                child: GeneratedRectangle2686Widget2(),
              ),
              Positioned(
                left: 52.0,
                top: 739.0,
                right: null,
                bottom: null,
                width: 190.0,
                height: 40.0,
                child: GeneratedRectangle2687Widget16(),
              ),
              Positioned(
                left: 99.0,
                top: 744.0,
                right: null,
                bottom: null,
                width: 69.0,
                height: 35.0,
                child: GeneratedKeluarWidget3(),
              ),
              Positioned(
                left: 67.0,
                top: 70.0,
                right: null,
                bottom: null,
                width: 160.0,
                height: 160.0,
                child: GeneratedRectangle2676Widget3(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.11864406779661017;

                  final double height =
                      constraints.maxHeight * 0.041469194312796206;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.6711864406779661,
                        y: constraints.maxHeight * 0.8779620853080569,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratediconlogoutWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.11864406779661017;

                  final double height =
                      constraints.maxHeight * 0.041469194312796206;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.8203389830508474,
                        y: constraints.maxHeight * 0.024881516587677725,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratediconarrowbackoutlineWidget3(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 26.0,
                top: 334.0,
                right: null,
                bottom: null,
                width: 230.0,
                height: 283.0,
                child: GeneratedProfilWidget3(),
              )
            ]),
      ),
    ));
  }
}
