import 'package:flutter/material.dart';
import 'package:flutterapp/pestakurentapp/generatedtable1widget1/generated/GeneratedTableWidget7.dart';

/* Component Table 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTable1Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 240.0,
      height: 108.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 240.0,
              height: 108.0,
              child: GeneratedTableWidget7(),
            )
          ]),
    ));
  }
}
