import 'package:flutter/material.dart';
import 'package:flutterapp/pestakurentapp/generatedberandawidget9/generated/GeneratedEditWidget7.dart';
import 'package:flutterapp/pestakurentapp/generatedberandawidget9/generated/GeneratedGroup14Widget5.dart';
import 'package:flutterapp/pestakurentapp/generatedberandawidget9/generated/GeneratedDaftarWidget27.dart';
import 'package:flutterapp/pestakurentapp/generatedberandawidget9/generated/GeneratedIconlyLightOutlineProfileWidget3.dart';
import 'package:flutterapp/pestakurentapp/generatedberandawidget9/generated/GeneratedIconlyBulkEditWidget3.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/pestakurentapp/generatedberandawidget9/generated/GeneratedMasukWidget36.dart';
import 'package:flutterapp/pestakurentapp/generatedberandawidget9/generated/GeneratedDeleteWidget11.dart';
import 'package:flutterapp/pestakurentapp/generatedberandawidget9/generated/GeneratedIconsaxLinearshoppingcartWidget2.dart';
import 'package:flutterapp/pestakurentapp/generatedberandawidget9/generated/GeneratedDeleteWidget7.dart';
import 'package:flutterapp/pestakurentapp/generatedberandawidget9/generated/GeneratedDeleteWidget9.dart';
import 'package:flutterapp/pestakurentapp/generatedberandawidget9/generated/GeneratedGroup5Widget14.dart';
import 'package:flutterapp/pestakurentapp/generatedberandawidget9/generated/GeneratedGroup7Widget6.dart';
import 'package:flutterapp/pestakurentapp/generatedberandawidget9/generated/GeneratedGroup7167Widget2.dart';
import 'package:flutterapp/pestakurentapp/generatedberandawidget9/generated/GeneratedLine61Widget4.dart';
import 'package:flutterapp/pestakurentapp/generatedberandawidget9/generated/GeneratedEditWidget8.dart';
import 'package:flutterapp/pestakurentapp/generatedberandawidget9/generated/GeneratedGroup7166Widget9.dart';

/* Frame beranda
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBerandaWidget9 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
          LayoutBuilder(
              builder: (BuildContext context, BoxConstraints constraints) {
            return SingleChildScrollView(
              scrollDirection: Axis.vertical,
              child: Container(
                  height: 1024.0,
                  child: Stack(children: [
                    Container(
                        width: constraints.maxWidth,
                        child: Container(
                          width: 1440.0,
                          height: 1024.0,
                          child: Stack(
                              fit: StackFit.expand,
                              alignment: Alignment.center,
                              overflow: Overflow.visible,
                              children: [
                                ClipRRect(
                                  borderRadius: BorderRadius.zero,
                                  child: Container(
                                    color: Color.fromARGB(255, 243, 239, 239),
                                  ),
                                ),
                                Positioned(
                                  left: 231.0,
                                  top: 607.0,
                                  right: null,
                                  bottom: null,
                                  width: 1144.0,
                                  height: 48.0,
                                  child: GeneratedGroup7Widget6(),
                                ),
                                Positioned(
                                  left: 36.0,
                                  top: 275.0,
                                  right: null,
                                  bottom: null,
                                  width: 1380.0,
                                  height: 300.0,
                                  child: GeneratedGroup14Widget5(),
                                ),
                                Positioned(
                                  left: 76.0,
                                  top: 687.0,
                                  right: null,
                                  bottom: null,
                                  width: 1299.0,
                                  height: 282.0,
                                  child: GeneratedGroup7167Widget2(),
                                ),
                                Positioned(
                                  left: 560.0,
                                  top: 839.0,
                                  right: null,
                                  bottom: null,
                                  width: 168.0,
                                  height: 108.0,
                                  child: GeneratedGroup7166Widget9(),
                                ),
                                Positioned(
                                  left: 0.0,
                                  top: 0.0,
                                  right: 0.0,
                                  bottom: 0.0,
                                  width: null,
                                  height: null,
                                  child: LayoutBuilder(builder:
                                      (BuildContext context,
                                          BoxConstraints constraints) {
                                    final double width =
                                        constraints.maxWidth * 0.025;

                                    final double height =
                                        constraints.maxHeight * 0.03515625;

                                    return Stack(children: [
                                      TransformHelper.translate(
                                          x: constraints.maxWidth *
                                              0.9152777777777777,
                                          y: constraints.maxHeight *
                                              0.275390625,
                                          z: 0,
                                          child: Container(
                                            width: width,
                                            height: height,
                                            child:
                                                GeneratedIconlyBulkEditWidget3(),
                                          ))
                                    ]);
                                  }),
                                ),
                                Positioned(
                                  left: 1375.0,
                                  top: 607.0,
                                  right: null,
                                  bottom: null,
                                  width: 48.0,
                                  height: 48.0,
                                  child: GeneratedDeleteWidget7(),
                                ),
                                Positioned(
                                  left: 1305.7537841796875,
                                  top: 344.251708984375,
                                  right: null,
                                  bottom: null,
                                  width: 48.0,
                                  height: 48.0,
                                  child: GeneratedEditWidget7(),
                                ),
                                Positioned(
                                  left: 1363.0,
                                  top: 285.0,
                                  right: null,
                                  bottom: null,
                                  width: 48.0,
                                  height: 48.0,
                                  child: GeneratedDeleteWidget9(),
                                ),
                                Positioned(
                                  left: 858.0,
                                  top: 847.0,
                                  right: null,
                                  bottom: null,
                                  width: 48.0,
                                  height: 48.0,
                                  child: GeneratedDeleteWidget11(),
                                ),
                                Positioned(
                                  left: 810.0,
                                  top: 847.0,
                                  right: null,
                                  bottom: null,
                                  width: 48.0,
                                  height: 48.0,
                                  child: GeneratedEditWidget8(),
                                ),
                                Positioned(
                                  left: 1286.0,
                                  top: 47.0,
                                  right: null,
                                  bottom: null,
                                  width: 87.0,
                                  height: 41.0,
                                  child: GeneratedMasukWidget36(),
                                ),
                                Positioned(
                                  left: 1195.0,
                                  top: 47.0,
                                  right: null,
                                  bottom: null,
                                  width: 79.0,
                                  height: 41.0,
                                  child: GeneratedDaftarWidget27(),
                                ),
                                Positioned(
                                  left: 1277.4908447265625,
                                  top: 90.99528503417969,
                                  right: null,
                                  bottom: null,
                                  width: 55.0,
                                  height: 1.0,
                                  child: GeneratedLine61Widget4(),
                                )
                              ]),
                        ))
                  ])),
            );
          }),
          Positioned(
            left: 80.0,
            top: 122.0,
            right: null,
            bottom: null,
            width: 1141.0,
            height: 90.0,
            child: GeneratedGroup5Widget14(),
          ),
          Positioned(
            left: 1248.0,
            top: 122.0,
            right: null,
            bottom: null,
            width: 78.0,
            height: 78.0,
            child: GeneratedIconsaxLinearshoppingcartWidget2(),
          ),
          Positioned(
            left: 1132.0,
            top: 45.0,
            right: null,
            bottom: null,
            width: 31.68000030517578,
            height: 39.74079895019531,
            child: GeneratedIconlyLightOutlineProfileWidget3(),
          )
        ]));
  }
}
