import 'package:flutter/material.dart';
import 'package:flutterapp/pestakurentapp/generatedkofirmasipembayaranwidget/generated/GeneratedRectangle2668Widget.dart';
import 'package:flutterapp/pestakurentapp/generatedkofirmasipembayaranwidget/generated/GeneratedRectangle2670Widget.dart';
import 'package:flutterapp/pestakurentapp/generatedkofirmasipembayaranwidget/generated/GeneratedRectangle2669Widget.dart';
import 'package:flutterapp/pestakurentapp/generatedkofirmasipembayaranwidget/generated/GeneratedLine39Widget.dart';
import 'package:flutterapp/pestakurentapp/generatedkofirmasipembayaranwidget/generated/GeneratedSelamatpembayaanandaberhasilWidget.dart';
import 'package:flutterapp/pestakurentapp/generatedkofirmasipembayaranwidget/generated/GeneratedLine38Widget.dart';
import 'package:flutterapp/pestakurentapp/generatedkofirmasipembayaranwidget/generated/GeneratedGroup7118Widget.dart';
import 'package:flutterapp/pestakurentapp/generatedkofirmasipembayaranwidget/generated/GeneratedGroup7119Widget.dart';
import 'package:flutterapp/pestakurentapp/generatedkofirmasipembayaranwidget/generated/GeneratedKeBerandaWidget.dart';

/* Component kofirmasi pembayaran
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedKofirmasipembayaranWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 37.0,
                top: 65.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 35.0,
                child: GeneratedRectangle2668Widget(),
              ),
              Positioned(
                left: 78.0,
                top: 159.0,
                right: null,
                bottom: null,
                width: 219.0,
                height: 219.0,
                child: GeneratedRectangle2669Widget(),
              ),
              Positioned(
                left: 78.0,
                top: 159.0,
                right: null,
                bottom: null,
                width: 309.7127685546875,
                height: 1.0,
                child: GeneratedLine38Widget(),
              ),
              Positioned(
                left: 297.0,
                top: 159.0,
                right: null,
                bottom: null,
                width: 309.7127685546875,
                height: 1.0,
                child: GeneratedLine39Widget(),
              ),
              Positioned(
                left: 26.0,
                top: 455.0,
                right: null,
                bottom: null,
                width: 322.0,
                height: 75.0,
                child: GeneratedRectangle2670Widget(),
              ),
              Positioned(
                left: 75.0,
                top: 578.0,
                right: null,
                bottom: null,
                width: 225.0,
                height: 50.0,
                child: GeneratedGroup7119Widget(),
              ),
              Positioned(
                left: 84.0,
                top: 590.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 25.0,
                child: GeneratedGroup7118Widget(),
              ),
              Positioned(
                left: 134.0,
                top: 590.0,
                right: null,
                bottom: null,
                width: 140.0,
                height: 26.0,
                child: GeneratedKeBerandaWidget(),
              ),
              Positioned(
                left: 45.0,
                top: 71.0,
                right: null,
                bottom: null,
                width: 286.0,
                height: 26.0,
                child: GeneratedSelamatpembayaanandaberhasilWidget(),
              )
            ]),
      ),
    ));
  }
}
