import 'package:flutter/material.dart';
import 'package:flutterapp/pestakurentapp/generatedberandawidget4/generated/GeneratedGroup16Widget.dart';
import 'package:flutterapp/pestakurentapp/generatedberandawidget4/generated/GeneratedGroup7Widget1.dart';
import 'package:flutterapp/pestakurentapp/generatedberandawidget4/generated/GeneratedGroup5Widget8.dart';
import 'package:flutterapp/pestakurentapp/generatedberandawidget4/generated/GeneratedGroup6Widget1.dart';
import 'package:flutterapp/pestakurentapp/generatedberandawidget4/generated/GeneratedGroup14Widget.dart';

/* Component beranda
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBerandaWidget4 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1024.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1440.0,
                      height: 1024.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 64.0,
                              top: 150.0,
                              right: null,
                              bottom: null,
                              width: 1312.0,
                              height: 90.0,
                              child: GeneratedGroup5Widget8(),
                            ),
                            Positioned(
                              left: 1016.0,
                              top: 40.0,
                              right: null,
                              bottom: null,
                              width: 384.0,
                              height: 50.0,
                              child: GeneratedGroup6Widget1(),
                            ),
                            Positioned(
                              left: 45.0,
                              top: 600.0,
                              right: null,
                              bottom: null,
                              width: 1351.0,
                              height: 80.0,
                              child: GeneratedGroup7Widget1(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 270.0,
                              right: null,
                              bottom: null,
                              width: 1400.0,
                              height: 300.0,
                              child: GeneratedGroup14Widget(),
                            ),
                            Positioned(
                              left: 74.0,
                              top: 700.0,
                              right: null,
                              bottom: null,
                              width: 1292.0,
                              height: 282.0,
                              child: GeneratedGroup16Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
