import 'package:flutter/material.dart';

/* UndefinedNode Masuk
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMasukWidget19 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
