import 'package:flutter/material.dart';
import 'package:flutterapp/pestakurentapp/generatedkeranjangwidget/generated/GeneratedGroup7108Widget.dart';
import 'package:flutterapp/pestakurentapp/generatedkeranjangwidget/generated/GeneratedGroup7123Widget.dart';
import 'package:flutterapp/pestakurentapp/generatedkeranjangwidget/generated/GeneratedRectangle2640Widget.dart';
import 'package:flutterapp/pestakurentapp/generatedkeranjangwidget/generated/GeneratedGroup7124Widget.dart';

/* Component keranjang
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedKeranjangWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 19.0,
                top: 62.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedGroup7123Widget(),
              ),
              Positioned(
                left: 327.0,
                top: 62.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedGroup7124Widget(),
              ),
              Positioned(
                left: 37.0,
                top: 110.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 254.0,
                child: GeneratedRectangle2640Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 380.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 432.0,
                child: GeneratedGroup7108Widget(),
              )
            ]),
      ),
    ));
  }
}
