import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/pestakurentapp/generatedmasukwidget24/generated/GeneratedGroup7071Widget6.dart';
import 'package:flutterapp/pestakurentapp/generatedmasukwidget24/generated/GeneratedDesktop6Widget1.dart';
import 'package:flutterapp/pestakurentapp/generatedmasukwidget24/generated/GeneratedMasukWidget25.dart';
import 'package:flutterapp/pestakurentapp/generatedmasukwidget24/generated/GeneratedRectangle2698Widget3.dart';
import 'package:flutterapp/pestakurentapp/generatedmasukwidget24/generated/GeneratedMasukWidget26.dart';

/* Component masuk
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMasukWidget24 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: LayoutBuilder(
        builder: (BuildContext context, BoxConstraints constraints) {
      return SingleChildScrollView(
        scrollDirection: Axis.vertical,
        child: Container(
            height: 1024.0,
            child: Stack(children: [
              Container(
                  width: constraints.maxWidth,
                  child: Container(
                    width: 1440.0,
                    height: 1024.0,
                    child: Stack(
                        fit: StackFit.expand,
                        alignment: Alignment.center,
                        overflow: Overflow.visible,
                        children: [
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: LayoutBuilder(builder: (BuildContext context,
                                BoxConstraints constraints) {
                              final double width = constraints.maxWidth;

                              final double height = constraints.maxHeight;

                              return Stack(children: [
                                TransformHelper.translate(
                                    x: 0,
                                    y: 0,
                                    z: 0,
                                    child: Container(
                                      width: width,
                                      height: height,
                                      child: GeneratedDesktop6Widget1(),
                                    ))
                              ]);
                            }),
                          ),
                          Positioned(
                            left: 720.0,
                            top: 421.0,
                            right: null,
                            bottom: null,
                            width: 569.9697265625,
                            height: 172.99996948242188,
                            child: GeneratedGroup7071Widget6(),
                          ),
                          Positioned(
                            left: 44.0,
                            top: 118.0,
                            right: null,
                            bottom: null,
                            width: 203.0,
                            height: 29.0,
                            child: GeneratedMasukWidget25(),
                          ),
                          Positioned(
                            left: 856.0,
                            top: 648.0,
                            right: null,
                            bottom: null,
                            width: 330.0,
                            height: 65.0,
                            child: GeneratedRectangle2698Widget3(),
                          ),
                          Positioned(
                            left: 955.0,
                            top: 669.0,
                            right: null,
                            bottom: null,
                            width: 137.0,
                            height: 29.0,
                            child: GeneratedMasukWidget26(),
                          )
                        ]),
                  ))
            ])),
      );
    }));
  }
}
